### ISSUE TITLE
Is there any to create empty folder?

### ISSUE THREAD

**Issue by sawyer1379416087** [scosman/zipstreamer#33]
in some sence, I need a empty folder on zip, is there any way to it?

now I can not start empty path wothout URL

**Comment by scosman** [comment]
Nothing is built in to support this. Out of curiosity: what’s the use case?

Probably not something I’ll find time to build since not a common request. I would accept a PR if it was clean, and you can always fork. 

Depending on what platforms you are targeting, putting and empty hidden file in the folder might do the trick (‘.hidden’)
